# Generated by Django 4.2.6 on 2023-11-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
