# Generated by Django 4.2.6 on 2023-12-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=26),
        ),
    ]
